### ISSUE TITLE
init.d/networking isn't portable.

### ISSUE THREAD

**Issue by siers** [viccherubini/get-shit-done#10]
That's some ubuntu/debian magick. Say, arch has only /etc/rc.d/network, and it's not really needed, as far as I can tell, and I think that line's redundant and should be removed. (I'm talking about the line 34, of course.)

```
    % sudo get-shit-done play
    sh: /etc/init.d/networking: No such file or directory
```

**Comment by viccherubini** [comment]
Well I use Ubuntu, so it works for me :)

It's not entirely necessary unless you want the effects to immediately take effect. I just hard code it in there to avoid having a whole configuration file for a very basic script.
