### ISSUE TITLE
Mac OS X /etc/init.d/networking equivalent?

### ISSUE THREAD

**Issue by jrhorn424** [viccherubini/get-shit-done#12]
A quick Google search turned up nothing. There must be some network daemon at work, since programs like [Freedom](http://macfreedom.com/) and [Concentrate](http://getconcentrating.com/) can block networking and specific sites, respectively. Any ideas?

**Comment by jrhorn424** [comment]
The script still seems to work, even though I don't see /etc/init.d/networking on my machine... odd?

**Comment by galvez** [comment]
```
sudo dscacheutil -flushcache
```

**Comment by saalaa** [comment]
Changes to /etc/hosts are taken into account immediately. In other words, networking restart is not needed.
