### ISSUE TITLE
Can't turn off work mode

### ISSUE THREAD

**Issue by tassock** [viccherubini/get-shit-done#26]
I installed get-shit-done on my mac and turned on work mode with "sudo get-shit-done work". Distracting sites are being blocked and work is getting done, but I can't turn it off. 

Can't...stop...working! This is more hardcore than I expected! 

Anyhow, so "sudo get-shit-done play" executes without response and doesn't turn it off. "sudo get-shit-done work" replies with "Work mode already set.", so the path configuration to the executable would seem to be set properly. Any idea what could be going wrong? Thanks!

**Comment by tassock** [comment]
For anyone experiencing this issue, I've gotten back to play mode manually by deleting the sites in /etc/hosts, then running "dscacheutil -flushcache". So much for getting work done!

**Comment by jingchen01** [comment]
me too, I have to reinstall
