### ISSUE TITLE
Needs locally editable list of blocked sites

### ISSUE THREAD

**Issue by sgricci** [viccherubini/get-shit-done#6]
The blocked sites that come with the script by default are lacking.

Needs locally modifiable, installation specific lists.

If I get time, I will work on it and submit a patch, but I believe it needs to be done regardless.

**Comment by viccherubini** [comment]
Sounds good, it's also pretty easy to just update the source and add the sites you visit often.

**Comment by sgricci** [comment]
Yeah, just figuring that any changes that get integrated then have to be merged everytime.

Just makes it easier for me personally, and I assume others as well.

**Comment by viccherubini** [comment]
Sounds good!

**Comment by soopercorp** [comment]
I'm not sure if you're proposing exactly this, but we could have addsite, removesite options to change sites on-the-fly.

**Comment by keramidasceid** [comment]
i believe its easier sites to be saved to a txt file so user can see and edit them easier or through terminal like hardikr said

**Comment by viccherubini** [comment]
You can do this already. Closing this issue.
